/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package kalgory:component@0.1.0;

world block {
    export execute: func(payload: list<u8>) -> result<list<u8>>;
}
