name: CI
on:
  push: {}
  pull_request: {}

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov wasmtime componentize-py
      - name: Test with pytest
        run: python3 -m pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=kalgory --cov-report=xml --cov-report=html
